In [1]:
from model.wavenet import WaveNet
from model.conv_encoder import ConvEncoder, ConvDecoder
from model.vq_vae import VQ_VAE

from vq_vae_trainer import VQ_VAE_Trainer

In [2]:
############################################################
# Current VQ-VAE implementation here
# - Input audio
# ---> Conv Encoder (Downsample)
# ---> VQ (Latent space)
# ---> Conv Decoder (Upsample)
# ---> WaveNet (Generate)
# - Output audio
############################################################
#wavenet = WaveNet()
#conv_encoder = ConvEncoder()
vq = VQ_VAE()

Model: "Convolutional-Encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 16000, 1)]        0         
_________________________________________________________________
conv1d (Conv1D)              (None, 8000, 256)         1280      
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 4000, 256)         262400    
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 2000, 256)         262400    
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 1000, 256)         262400    
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 500, 256)          262400    
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 250, 256)

Model: "Convolutional-Decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, None, 32)]        0         
_________________________________________________________________
conv1d_transpose (Conv1DTran (None, None, 256)         33024     
_________________________________________________________________
conv1d_transpose_1 (Conv1DTr (None, None, 256)         262400    
_________________________________________________________________
conv1d_transpose_2 (Conv1DTr (None, None, 256)         262400    
_________________________________________________________________
conv1d_transpose_3 (Conv1DTr (None, None, 256)         262400    
_________________________________________________________________
conv1d_transpose_4 (Conv1DTr (None, None, 256)         262400    
_________________________________________________________________
conv1d_transpose_5 (Conv1DTr (None, None, 256

In [12]:
import tensorflow as tf

## Dummy dataset to test architecture
def generator(): 
    x = tf.random.normal(shape=(16000,1))
    yield (x, x)
    
ds = tf.data.Dataset.from_generator(generator, output_types=(tf.float32, tf.float32))
print(ds)

for x in ds:
    print(x)
    break
    
trainer = VQ_VAE_Trainer(vq)
trainer.train(ds)

<FlatMapDataset shapes: (<unknown>, <unknown>), types: (tf.float32, tf.float32)>
(<tf.Tensor: shape=(16000, 1), dtype=float32, numpy=
array([[ 2.9762292 ],
       [-2.2403057 ],
       [ 0.8876686 ],
       ...,
       [-1.3659022 ],
       [ 0.67921096],
       [ 0.34868836]], dtype=float32)>, <tf.Tensor: shape=(16000, 1), dtype=float32, numpy=
array([[ 2.9762292 ],
       [-2.2403057 ],
       [ 0.8876686 ],
       ...,
       [-1.3659022 ],
       [ 0.67921096],
       [ 0.34868836]], dtype=float32)>)
Initializing from scratch.


NameError: name 'configs' is not defined