In [1]:
from model.wavenet import WaveNet
from model.conv_encoder import ConvEncoder, ConvDecoder
from model.vq_vae import VQ_VAE

from vq_vae_trainer import VQ_VAE_Trainer

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

In [2]:
############################################################
# Current VQ-VAE implementation here
# - Input audio
# ---> Conv Encoder (Downsample)
# ---> VQ (Latent space)
# ---> Conv Decoder (Upsample)
# ---> WaveNet (Generate)
# - Output audio
############################################################
#wavenet = WaveNet()
#conv_encoder = ConvEncoder()
vq = VQ_VAE()

Model: "Convolutional-Encoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 16000, 1)]        0         
_________________________________________________________________
conv1d (Conv1D)              (None, 8000, 32)          160       
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 4000, 32)          4128      
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 2000, 32)          4128      
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 1000, 32)          4128      
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 500, 32)           4128      
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 250, 32) 

Model: "Convolutional-Decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, None, 32)]        0         
_________________________________________________________________
conv1d_transpose (Conv1DTran (None, None, 32)          4128      
_________________________________________________________________
conv1d_transpose_1 (Conv1DTr (None, None, 32)          4128      
_________________________________________________________________
conv1d_transpose_2 (Conv1DTr (None, None, 32)          4128      
_________________________________________________________________
conv1d_transpose_3 (Conv1DTr (None, None, 32)          4128      
_________________________________________________________________
conv1d_transpose_4 (Conv1DTr (None, None, 32)          4128      
_________________________________________________________________
conv1d_transpose_5 (Conv1DTr (None, None, 32)

In [3]:
from scipy.io.wavfile import read
import os
DATA_PATH = r"/home/rithomas/data/IDMT-SMT-GUITAR_V2/dataset1/Fender_Strat_Clean_Neck_SC/audio"
p = os.path.join(DATA_PATH, 'G53-40100-1111-00001.wav')
print(read(p))

(44100, array([6, 5, 4, ..., 0, 0, 0], dtype=int16))


In [4]:
import tensorflow as tf
import numpy as np

DATA_PATH='/home/rithomas/data/test_preprocessed.npy'
raw_dataset = np.load(DATA_PATH)
print(raw_dataset)
## Dummy dataset to test architecture
def generator():
    for x in raw_dataset:
        yield tf.expand_dims(x, axis=-1)
    
ds = tf.data.Dataset.from_generator(generator, output_types=tf.int32)
ds = ds.batch(4)
print(ds)

TRAINING_CONFIGS = {
    'model_path': '/home/rithomas/cache/test_model',
    'learning_rate': 0.0001,
    'num_epochs': 100,
    'print_every': 100
}
trainer = VQ_VAE_Trainer(vq, TRAINING_CONFIGS)
trainer.train(ds)

[[ 1.50666323e+00  3.61601279e+00  3.06986080e+00 ... -1.30838097e-01
   1.63293566e-01 -2.53080688e-01]
 [-2.94721895e+01 -4.44529436e+01 -3.97607743e+01 ...  1.30250276e+00
  -1.93923285e+00  3.58419131e+00]
 [-2.88367472e+00 -7.13141847e+00 -4.68943032e+00 ...  1.70556720e-01
  -2.31031208e-01  3.97306949e-01]
 ...
 [-2.01412884e+00 -3.55152405e+00 -2.92396460e+00 ...  1.17351797e-01
  -1.72185101e-01  2.98904466e-01]
 [-4.49997355e+00 -7.57414758e+00 -6.77552881e+00 ... -5.16576875e-01
  -2.59515366e-01  5.47160105e-01]
 [-1.84635341e-01 -1.50365003e+00 -8.98843271e-01 ... -3.05238402e-02
   1.05169126e-02  1.09047531e-02]]
<BatchDataset shapes: <unknown>, types: tf.int32>
Initializing from scratch.
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(6.230554, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(6.2078733, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(6.1856995, shape=(

tf.Tensor(5.083998, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0737977, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0922422, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0787296, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0451612, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.041654, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.083426, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0805864, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.047585, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0523663, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,

tf.Tensor(5.0598593, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.04778, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0155897, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0134034, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056445, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.054823, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022989, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.02889, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.053153, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.058086, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dt

tf.Tensor(5.015226, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0130634, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056127, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0545235, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022708, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0286274, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0529084, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057857, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.018573, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045302, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.013061, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056126, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0545225, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0227056, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028622, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.05291, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578547, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.018575, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0452995, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0511665, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.0545225, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0226893, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0285854, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052923, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057843, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0186048, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0452833, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051177, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.041841, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004941, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,)

tf.Tensor(5.022668, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028539, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0529385, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.05784, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0186424, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0452647, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0511913, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0418606, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004919, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051033, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.0284057, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0529838, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578756, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.018781, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045208, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051222, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0419307, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0048656, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.050983, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0575624, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,

tf.Tensor(5.0578613, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.018751, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045204, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0512304, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0419526, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0048366, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.050946, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0575495, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0511723, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.048199, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,

tf.Tensor(5.045294, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051171, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.041831, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004947, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0510664, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057578, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0512443, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0481024, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0394874, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0594335, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,)

tf.Tensor(5.0418324, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004943, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051063, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057578, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0512424, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0481067, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0394926, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0594296, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.047396, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.015216, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,)

tf.Tensor(5.004932, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051054, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0575776, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051238, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0481143, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.039505, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.059419, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0473995, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.015209, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0130506, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.0510206, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0575757, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051227, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0481486, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0395684, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0593767, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.047419, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0151825, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.01302, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0561433, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,

tf.Tensor(5.0512176, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0481744, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.039619, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0593452, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0474334, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.015163, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.012997, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056149, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.054508, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022585, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.0394764, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.059445, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0473905, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0152264, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.013062, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056125, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0545235, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022711, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028632, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052906, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.059445, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0473905, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0152264, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.013062, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056125, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0545235, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022711, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028632, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052906, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578594, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.0473905, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0152264, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.013062, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056125, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0545235, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022711, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028632, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052906, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578594, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0185704, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,)

tf.Tensor(5.013062, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.056125, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0545235, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022711, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028632, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052906, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578594, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0185704, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045305, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051164, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), 

tf.Tensor(5.0545235, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.022711, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028632, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052906, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578594, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0185704, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045305, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051164, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0418277, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004961, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.022711, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.028632, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052906, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578594, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0185704, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045305, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051164, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0418277, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004961, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0510783, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.028632, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.052906, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0578594, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0185704, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045305, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051164, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0418277, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004961, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0510783, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057578, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.0578594, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0185704, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.045305, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051164, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0418277, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004961, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0510783, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057578, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0512495, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.048094, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,)

tf.Tensor(5.045305, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.051164, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0418277, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004961, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0510783, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057578, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0512495, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.048094, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0394764, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.059445, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,),

tf.Tensor(5.0418277, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.004961, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0510783, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057578, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0512495, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.048094, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0394764, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.059445, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0473905, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0152264, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,

tf.Tensor(5.004961, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0510783, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.057578, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0512495, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.048094, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0394764, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.059445, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0473905, shape=(), dtype=float32)
tf.Tensor([    2 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.0152264, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,), dtype=int32)
tf.Tensor(5.013062, shape=(), dtype=float32)
tf.Tensor([    4 32000     1], shape=(3,)